// <auto-generated />
namespace Prosumer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class context_opdateret : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(context_opdateret));
        
        string IMigrationMetadata.Id
        {
            get { return "201805240826159_context_opdateret"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
